//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlythiduakhenthuongEntities : DbContext
    {
        public quanlythiduakhenthuongEntities()
            : base("name=quanlythiduakhenthuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<qltdkt_baocaothidua> qltdkt_baocaothidua { get; set; }
        public virtual DbSet<qltdkt_baocaothongke> qltdkt_baocaothongke { get; set; }
        public virtual DbSet<qltdkt_dangkythidua> qltdkt_dangkythidua { get; set; }
        public virtual DbSet<qltdkt_danhhieu> qltdkt_danhhieu { get; set; }
        public virtual DbSet<qltdkt_dm_capkykhenthuong> qltdkt_dm_capkykhenthuong { get; set; }
        public virtual DbSet<qltdkt_dm_chucvu> qltdkt_dm_chucvu { get; set; }
        public virtual DbSet<qltdkt_dm_chuky> qltdkt_dm_chuky { get; set; }
        public virtual DbSet<qltdkt_dm_danhhieuthidua> qltdkt_dm_danhhieuthidua { get; set; }
        public virtual DbSet<qltdkt_dm_donvi> qltdkt_dm_donvi { get; set; }
        public virtual DbSet<qltdkt_dm_donviphatdong> qltdkt_dm_donviphatdong { get; set; }
        public virtual DbSet<qltdkt_dm_hinhthuckhenthuong> qltdkt_dm_hinhthuckhenthuong { get; set; }
        public virtual DbSet<qltdkt_dm_nhanvien> qltdkt_dm_nhanvien { get; set; }
        public virtual DbSet<qltdkt_dm_role> qltdkt_dm_role { get; set; }
        public virtual DbSet<qltdkt_dm_thidua> qltdkt_dm_thidua { get; set; }
        public virtual DbSet<qltdkt_dm_trinhdohocvan> qltdkt_dm_trinhdohocvan { get; set; }
        public virtual DbSet<qltdkt_groupuser> qltdkt_groupuser { get; set; }
        public virtual DbSet<qltdkt_groupuserbyroles> qltdkt_groupuserbyroles { get; set; }
        public virtual DbSet<qltdkt_hosokyyeu> qltdkt_hosokyyeu { get; set; }
        public virtual DbSet<qltdkt_hosothidua> qltdkt_hosothidua { get; set; }
        public virtual DbSet<qltdkt_ketquathidua> qltdkt_ketquathidua { get; set; }
        public virtual DbSet<qltdkt_khenthuong> qltdkt_khenthuong { get; set; }
        public virtual DbSet<qltdkt_thidua> qltdkt_thidua { get; set; }
        public virtual DbSet<qltdkt_user> qltdkt_user { get; set; }
        public virtual DbSet<qltdkt_userbygroup> qltdkt_userbygroup { get; set; }
    }
}
