//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_dm_role
    {
        public int id { get; set; }
        public string roleName { get; set; }
        public string roleUrl { get; set; }
        public Nullable<int> roleParent { get; set; }
        public Nullable<int> priority { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string @class { get; set; }
        public string styles { get; set; }
    }
}
