//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_dm_donvi
    {
        public int id { get; set; }
        public string tenDonVi { get; set; }
        public int idCha { get; set; }
        public System.DateTime ngayTao { get; set; }
        public System.DateTime ngayCapNhat { get; set; }
        public string anh { get; set; }
    }
}
