//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_hosothidua
    {
        public int id { get; set; }
        public Nullable<int> thiDuaId { get; set; }
        public Nullable<byte> kieuThiDua { get; set; }
        public string chiTietKieu { get; set; }
        public string toTrinh { get; set; }
        public string bienBanHopHoiDong { get; set; }
        public string sangKien { get; set; }
        public Nullable<byte> trangThai { get; set; }
        public string vanBanHuongDan { get; set; }
        public string xacNhanThue { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<bool> daXoa { get; set; }
        public string fileDinhKem { get; set; }
        public string fileBaoCaoThanhTich { get; set; }
        public string chiTietBaoCaoThanhTich { get; set; }
        public string tenHoSoThiDua { get; set; }
        public Nullable<System.DateTime> ngayPhatDong { get; set; }
        public string tenThiDua { get; set; }
        public string soHieu { get; set; }
    }
}
