//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_khenthuong
    {
        public int id { get; set; }
        public Nullable<byte> capKhenThuong { get; set; }
        public string quyetDinh { get; set; }
        public string soHieu { get; set; }
        public System.DateTime ngayKhenThuong { get; set; }
        public byte kieuKhenThuong { get; set; }
        public string moTaKieu { get; set; }
        public string capKyKhenThuong { get; set; }
        public string noiDungKhenThuong { get; set; }
        public string danhSachCaNhanKhenThuong { get; set; }
        public string tongTien { get; set; }
        public Nullable<bool> daTraoTang { get; set; }
        public Nullable<System.DateTime> ngayTraoTang { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public Nullable<byte> trangThai { get; set; }
        public Nullable<bool> daXoa { get; set; }
        public Nullable<byte> doiTuongThamGia { get; set; }
        public Nullable<decimal> tienThuong { get; set; }
        public Nullable<int> hinhThucKhenThuong { get; set; }
        public Nullable<int> tongTienThuong { get; set; }
        public string ghichuHTKT { get; set; }
        public Nullable<int> bophan { get; set; }
    }
}
