//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_hosokyyeu
    {
        public int id { get; set; }
        public int idDonVi { get; set; }
        public Nullable<int> idNhanVien { get; set; }
        public string anhDaiDien { get; set; }
        public string hoSoKyYeu { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public string chucNangNhiemVu { get; set; }
        public string soQDThanhLap { get; set; }
        public Nullable<byte> daXoa { get; set; }
        public Nullable<int> idDanhHieu { get; set; }
    }
}
