//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_danhhieu
    {
        public int id { get; set; }
        public Nullable<byte> idTenDanhHieu { get; set; }
        public string soHieu { get; set; }
        public Nullable<System.DateTime> ngayDanhHieu { get; set; }
        public string capKyKhenThuong { get; set; }
        public string noiDung { get; set; }
        public string danhSachCaNhanTapThe { get; set; }
        public Nullable<decimal> tienThuong { get; set; }
        public string fileGoc { get; set; }
        public Nullable<byte> hinhThucTraoTang { get; set; }
        public Nullable<bool> daTraoTang { get; set; }
        public Nullable<System.DateTime> ngayTraoTang { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<bool> daXoa { get; set; }
        public Nullable<byte> kieuDanhHieu { get; set; }
        public Nullable<int> namDanhHieu { get; set; }
        public string hinhAnhTraoTang { get; set; }
        public string tuNam { get; set; }
        public string denNam { get; set; }
        public string nguoiKy { get; set; }
        public Nullable<int> bophan { get; set; }
        public string ghiChuTT { get; set; }
    }
}
