//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_dangkythidua
    {
        public int id { get; set; }
        public int thiDuaId { get; set; }
        public int donViDangKyId { get; set; }
        public string noiDungDangKy { get; set; }
        public Nullable<bool> daBaoCao { get; set; }
        public string caNhanDangKy_KetQua { get; set; }
        public System.DateTime ngayDangKy { get; set; }
        public string fileDinhKem { get; set; }
        public string soHieu { get; set; }
        public Nullable<System.DateTime> ngayKetQua { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<byte> trangThaiThiDua { get; set; }
        public Nullable<byte> xepHangThiDua { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public string nhanXetChung { get; set; }
        public string nguoiKyDanhGia { get; set; }
        public string noiDungDanhGia { get; set; }
        public string fileBaoCao { get; set; }
        public Nullable<bool> daXoa { get; set; }
        public Nullable<bool> isCaNhanDangKy { get; set; }
    }
}
