//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_dm_donviphatdong
    {
        public int id { get; set; }
        public string tenPhatDong { get; set; }
        public string moTa { get; set; }
        public Nullable<byte> isCamKet { get; set; }
    }
}
