//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTDKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qltdkt_ketquathidua
    {
        public int id { get; set; }
        public int thiDuaId { get; set; }
        public int dangKyThiDuaId { get; set; }
        public string nhanXetChung { get; set; }
        public string nguoiKyDanhGia { get; set; }
        public string noiDungDanhGia { get; set; }
        public string fileBaoCao { get; set; }
    }
}
